### ISSUE TITLE
Documentacion

### ISSUE THREAD

**Issue by ravamo** [equipoimcre/alberges#1]
Añadir la documentación :

1. Configuración de nginx @ravamo 
2. Configuraciòn estandar  del proyecto @srteppei :
2.1 Compilación de proyecto teniendo en cuanta tanto la ruta de estaticos.
2.2 Compilación del backend o front

**Comment by srteppei** [comment]
He subido cambios en la wiki y lo de los estaticos esta en ejemplo dle fichero de nginx
