### ISSUE TITLE
CCAA-Provincias en el Burcador de Albergue

### ISSUE THREAD

**Issue by Luciamm23** [equipoimcre/alberges#3]
En el Buscador de Albergue, cuando escojo una CCAA no me restringe la elección de provincia. Me vuelven a salir las 50 provincias. Y al listar las 50, se organizan por CCAA, en vez de alfabéticamente. Es un poco lío. Sin embargo, cuando vas a crear un Albergue si te salen las provincias según la CCAA elegida.
En ninguna de las dos pantallas la lista de las CCAA está ordenada alfabéticamente. Habría que ordenarlo de alguna manera para facilitar la búsqueda en el desplegable.

**Comment by srteppei** [comment]
En el filtro no restringe porque no has de seleccionar una CCAA para poder filtrar por provincia, mientras que al crear un albergue si se ha de seleccionar primero.

En cuanto al tema de la ordenación la que me digas

**Comment by Luciamm23** [comment]
Ok, yo las ordenaría alfabeticamente para que sea más fácil si te pones a buscar en el listado

**Comment by srteppei** [comment]
Lo he cambiado para que el orden sea ascente

**Comment by ravamo** [comment]
he actualizado el codigo 

- npm run migrate
- node dist/src/main
Pero aun aparece las Comunidades autonomas sin ordenar.
![comunidades_autonoma](https://user-images.githubusercontent.com/47725050/190232330-33e0564e-12a7-4877-9251-ec0ced281520.JPG)
