### ISSUE TITLE
Erratas Pantalla Crear albergue

### ISSUE THREAD

**Issue by Luciamm23** [equipoimcre/alberges#4]
-	En Extremadura aparece Cádiz, y en Andalucía falta esta provincia.
-	Islas Baleares está escrito en castellano en la caja de CCAA y en catalán en el de Provincias.
- 	En los campos de Superficie, poner (m2)

**Comment by Luciamm23** [comment]
Sería algo así, pero como vamos "resumir" los textos de cada una de las preguntas, casi que lo dejaría y cuando estén los textos definitivos de cada pregunta incluiremos los metros cuadrados
![image](https://user-images.githubusercontent.com/101993706/189103059-d230e7b3-2f0f-4f12-8273-68269670167e.png)

**Comment by srteppei** [comment]
Entonces cierro este issue y ya en el de resumir los texto se pone la versión definitiva
