### ISSUE TITLE
ERROR dar de alta albergue

### ISSUE THREAD

**Issue by Luciamm23** [equipoimcre/alberges#6]
Cuando intento dar de alta un nuevo albergue, siendoadministrador, me sale este mensaje:

```json
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"http://10.98.139.5/api/shelter/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://10.98.139.5/api/shelter/: 400 Bad Request","error":{"statusCode":400,"message":"Bad request"}}
```

![image](https://user-images.githubusercontent.com/101993706/186895821-0a09b598-8f7b-4623-bf27-6302d4c15f7b.png)

**Comment by srteppei** [comment]
@Luciamm23  puedes pasar una captura de como has rellenado el formulario para que salta ese error ?

**Comment by srteppei** [comment]
Es la coma en la longitud y latitud. Es como en el excel es un punto en vez de una coma
